[package]
name = "libsvm-sys"
version = "3.24.0"
authors = ["Yu-Wei Wu <wusyong9104@gmail.com>"]
edition = "2018"
license = "BSD-3-Clause"
description = "FFI bindings to libsvm"

[build-dependencies]
cc = "1.0"
